import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { useNavigate } from "react-router-dom";

const Terms = () => {
  const navigate = useNavigate();
  return (
    <div className="min-h-screen bg-background">
      <div className="container mx-auto px-4 py-10 max-w-4xl">
        <div className="mb-6 flex items-center justify-between">
          <h1 className="text-3xl font-bold">Terms of Service</h1>
          <Button variant="outline" onClick={() => navigate('/')}>Back to Home</Button>
        </div>

        <Card className="shadow-soft">
          <CardHeader>
            <CardTitle>Terms of Service for Peta-Progress</CardTitle>
            <CardDescription>Last Updated: 30th October 2025</CardDescription>
          </CardHeader>
          <CardContent className="prose prose-sm max-w-none text-foreground">
            <p>Welcome to Peta-Progress! These Terms of Service ("Terms") govern your access to and use of the Peta-Progress task management services ("Service"). These Terms are a binding legal agreement between Petaera Technologies ("Peta-Progress," "we," or "us") and the entity agreeing to these terms ("Customer," "you").</p>
            <p>By creating an account, or by accessing or using the Service, you agree to be bound by these Terms.</p>

            <h3>1. The Service</h3>
            <p>Peta-Progress provides a workplace task and project management platform designed to help organizations and their teams manage work, track progress, and log daily activities ("Service").</p>

            <h3>2. Accounts</h3>
            <ul>
              <li><strong>Organization Account:</strong> To use the Service, a Customer must create an account. The Customer is responsible for all activity that occurs under its account, including the conduct of its authorized users.</li>
              <li><strong>User Accounts:</strong> The Customer may invite individuals (such as employees or contractors) to become "Users" of its account. The Customer is responsible for managing User access and ensuring all Users comply with these Terms and all applicable laws.</li>
              <li><strong>Responsibilities:</strong> You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account.</li>
            </ul>

            <h3>3. Customer and User Content</h3>
            <ul>
              <li><strong>Ownership:</strong> The Customer retains all rights, title, and ownership of all data, text, files, or other materials uploaded or generated by its Users within the Service ("Customer Content"). This includes all task descriptions, daily logs, and hours spent.</li>
              <li><strong>Our License to You:</strong> Peta-Progress claims no ownership over Customer Content. You grant Peta-Progress a worldwide, non-exclusive, limited license to access, use, host, store, and display Customer Content solely for the purpose of providing and improving the Service.</li>
              <li><strong>Your Responsibility:</strong> You (the Customer) represent that you have all necessary rights to upload Customer Content and that its use does not violate any third-party rights or applicable laws.</li>
            </ul>

            <h3>4. Acceptable Use</h3>
            <p>You agree not to use the Service to:</p>
            <ul>
              <li>Violate any law or regulation.</li>
              <li>Infringe on any third-party's intellectual property, privacy, or other rights.</li>
              <li>Upload any malicious code, viruses, or harmful data.</li>
              <li>Harass, abuse, or harm other individuals.</li>
              <li>Reverse-engineer or attempt to gain unauthorized access to the Service.</li>
            </ul>

            <h3>5. Termination</h3>
            <ul>
              <li><strong>By Customer:</strong> You may terminate your account at any time by contacting us.</li>
              <li><strong>By Peta-Progress:</strong> We reserve the right to suspend or terminate your account if you are in material breach of these Terms. We will provide reasonable notice where possible.</li>
              <li><strong>Effect of Termination:</strong> Upon termination, your right to use the Service will cease. We will provide you with an opportunity to export your Customer Content. After a defined period, we may delete all Customer Content from our systems.</li>
            </ul>

            <h3>6. Disclaimer of Warranties</h3>
            <p>The Service is provided "AS IS" without any warranties, express or implied. Peta-Progress does not guarantee that the Service will be uninterrupted, error-free, or secure.</p>

            <h3>7. Limitation of Liability</h3>
            <p>To the maximum extent permitted by law, Peta-Progress shall not be liable for any indirect, incidental, or consequential damages, or for any loss of data, profits, or revenue, arising out of your use of the Service.</p>

            <h3>8. Changes to Terms</h3>
            <p>We may modify these Terms from time to time. We will provide notice of material changes (e.g., via email or an in-app notification). Your continued use of the Service after changes become effective constitutes your acceptance of the new Terms.</p>

            <h3>9. Governing Law</h3>
            <p>These Terms shall be governed by the laws of [Your State/Country], without regard to its conflict of law principles.</p>

            <h3>10. Contact Us</h3>
            <p>If you have any questions about these Terms, please contact us at info@petaera.com.</p>
          </CardContent>
        </Card>
      </div>
    </div>
  );
};

export default Terms;


